menu:
  Home: [home, /]
  Blogs: [list-ul, /blogs]
  Works: [check-square-o, /works]
  "About me": [user, /about]
widgets:
- search
- category
- tag

excerpt_link: Read More

twitter:
  username:
  show_replies: false
  tweet_count: 5

addthis:
  enable: true
  pubid:
  facebook: true
  twitter: true
  google: true
  pinterest: true

fancybox: true

google_analytics: UA-76156966-1
rss:

comment_provider: facebook

# Facebook comment

# Disqus
disqus_shortname: JunkaiYang
